apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerid-frontend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: workerid-frontend
  template:
    metadata:
      labels:
        app: workerid-frontend
    spec:
      containers:
      - name: workerid-frontend
        image: chinooth/workerid-frontend:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec: # Use 'exec' for database check
            command:
              - "sh"
              - "-c"
              - "python check_db_connection.py" # 
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: 1.m
